import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'selector',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/widgets/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/entities/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/shared/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
    colors: {
      'COLOR_1': '#212121',
      'COLOR_2': '#2c2c2c',
      'COLOR_3': '#8774e1',
      'COLOR_4': '#686c72',
      'COLOR_5': '#111111',
      'COLOR_6': '#aaaaaa',
      'COLOR_7': '#0F0F0F',
      'COLOR_8': '#3390ec',
      'COLOR_9': '#dadce0',
      'COLOR_10': '#707579',
      'COLOR_11': '#4a95d6',
      'COLOR_12': '#282828',
      'COLOR_13': '#a2acb4',
      'COLOR_14': '#5b5b5a',
      'COLOR_15': '#e53935',
      'COLOR_16': '#f4f4f5',
      'COLOR_17': '#dbdbdb',
      'COLOR_18': '#EEFFDE',
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'black': '#000000',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#ff77e9',
      'bermuda': '#78dcca',
    },
  },
  plugins: [],
};
export default config;
