import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Dialogs } from "@/widgets/Dialogs";
import { Chat } from "@/widgets/Chat";
import ReactQueryProvider from "@/_app/providers/ReactQueryProvider";
import { redirect } from "next/navigation";

const inter = Roboto({ subsets: ["cyrillic"], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // if (1) {
  //   redirect('/auth');
  // }

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="flex">
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
