import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Dialogs } from "@/widgets/Dialogs";
import { Chat } from "@/widgets/Chat";
import ReactQueryProvider from "@/_app/providers/ReactQueryProvider";

const inter = Roboto({ subsets: ["cyrillic"], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="flex">
            <div className="min-w-64 max-w-64">
              <Dialogs className="h-screen overflow-x-auto" />
            </div>
            
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
