import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { cookies } from 'next/headers';
import "./globals.css";
import ReactQueryProvider from "@/_app/providers/ReactQueryProvider";
import { ThemeProvider } from "@/_app/providers/ThemeProvider";
import { Theme } from "@/shared/hooks/useTheme/useTheme";
import { CookiesProvider } from 'next-client-cookies/server';

const inter = Roboto({ subsets: ["cyrillic"], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <ReactQueryProvider>
            <ThemeProvider defaultTheme={cookies().get('theme')?.value as Theme || 'light'}>
              {children}
            </ThemeProvider>
          </ReactQueryProvider> 
        </CookiesProvider>
      </body>
    </html>
  );
}
